force-app/main/default/objects/PLM_Proposal__c/PLM_Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PLM_Proposal__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This is the description.</description>
    <label>Description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Proposal__c/fields/Proposal_Name__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Name__c</fullName>
    <description>This is the Proposal name.</description>
    <label>Proposal Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_WorkFront_Details__c/PLM_WorkFront_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>PLM WorkFront Details</label>
</CustomObject>

force-app/main/default/classes/PLM_CTRL_SendProjectToWorkFrontTest.cls
/**********************************************************************
Name: PLM_CTRL_SendProjectToWorkFrontTest()
Copyright © 2015 Salesforce
======================================================
======================================================
@Purpose: Test class.
======================================================
======================================================
History 
------- 
VERSION   AUTHOR                  DATE        DETAIL Description
1.0       Name : Abilash Patha   08/08/2019   INITIAL DEVELOPMENT CSR: 
***********************************************************************/
@isTest
public class PLM_CTRL_SendProjectToWorkFrontTest {

    @testSetup 
 static void testSetup(){
     
       PLM_Proposal__c testProposal =  new PLM_Proposal__c();
       testProposal.Proposal_Name__c = 'Proposa WorkFront';
       testProposal.Edition_Number__c = 1234;
       testProposal.Description__c = 'Prop Descr';
       insert testProposal;
     
       PLM_WorkFront_Details__c wfDetails =  new PLM_WorkFront_Details__c();
       wfDetails.End_Point_URL__c = 'https://wileycontent.sb01.workfront.com/attask/api/v9.0/project?';
       wfDetails.Api_Key__c = 'abcdef';
       insert wfDetails;
     
     }
  @isTest
    public static void invocableMethod(){
        
    }
}