force-app/main/default/objects/PLM_Product_Family__c/PLM_Product_Family__c.object-meta.xml
<CustomObject>
    <label>Product Family</label>
    <nameField>
        <displayFormat>PF-{0000000}</displayFormat>
        <label>Product Family #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Family</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PLM_Product_Family__c/fields/Copy_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Copy_Product_Family__c</fullName>
    <label>Copy Product Family</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Editor_Code__c.field-meta.xml
<CustomField>
    <fullName>Editor_Code__c</fullName>
    <label>Editor Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Editor_Name__c.field-meta.xml
<CustomField>
    <fullName>Editor_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Editor Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Product_Group_Origin_Description__c</field>
            <operation>equals</operation>
            <valueField>PLM_Editor__c.Location__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PLM_Editor__c</referenceTo>
    <relationshipLabel>Product Family</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Product_Family__c/fields/Full_Title__c.field-meta.xml
<CustomField>
    <fullName>Full_Title__c</fullName>
    <label>Full Title</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Global_Subject_Category_Code__c.field-meta.xml
<CustomField>
    <fullName>Global_Subject_Category_Code__c</fullName>
    <label>Global Subject Category Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Global_Subject_Category_Description__c.field-meta.xml
<CustomField>
    <fullName>Global_Subject_Category_Description__c</fullName>
    <label>Global Subject Category Description</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Group_Origin_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>GE Allocated</fullName>
            </value>
            <value>
                <fullName>GE Business</fullName>
            </value>
            <value>
                <fullName>GE Sciences</fullName>
            </value>
            <value>
                <fullName>GE School</fullName>
            </value>
            <value>
                <fullName>GE Microsoft</fullName>
            </value>
            <value>
                <fullName>GE Math and Statistics</fullName>
            </value>
            <value>
                <fullName>GE Engg &amp; Computer Sci</fullName>
            </value>
            <value>
                <fullName>GE Other</fullName>
            </value>
            <value>
                <fullName>GE Applied Markets</fullName>
            </value>
            <value>
                <fullName>GE Social Sciences/Culinary</fullName>
            </value>
            <value>
                <fullName>Undefined</fullName>
            </value>
            <value>
                <fullName>PD Allocated</fullName>
            </value>
            <value>
                <fullName>PD Business</fullName>
            </value>
            <value>
                <fullName>PD Consumer</fullName>
            </value>
            <value>
                <fullName>PD Education</fullName>
            </value>
            <value>
                <fullName>PD Other</fullName>
            </value>
            <value>
                <fullName>PD Psychology</fullName>
            </value>
            <value>
                <fullName>PD Architecture</fullName>
            </value>
            <value>
                <fullName>PD Technology</fullName>
            </value>
            <value>
                <fullName>STMS Allocated</fullName>
            </value>
            <value>
                <fullName>STMS Life Sciences</fullName>
            </value>
            <value>
                <fullName>STMS Health Sciences</fullName>
            </value>
            <value>
                <fullName>STMS Other</fullName>
            </value>
            <value>
                <fullName>STMS Physical Sciences &amp; Engg</fullName>
            </value>
            <value>
                <fullName>STMS Social Sci &amp; Humanities</fullName>
            </value>
            <value>
                <fullName>HE Allocated</fullName>
            </value>
            <value>
                <fullName>HE Business</fullName>
            </value>
            <value>
                <fullName>HE Sciences</fullName>
            </value>
            <value>
                <fullName>HE School</fullName>
            </value>
            <value>
                <fullName>HE Microsoft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Number_Of_Volumes__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Volumes__c</fullName>
    <label>Number Of Volumes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Primary_Market_Category__c.field-meta.xml
<CustomField>
    <fullName>Primary_Market_Category__c</fullName>
    <label>Primary Market Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Textbook</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Reference</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Product_Family__c/fields/Product_Family_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_Name__c</fullName>
    <label>Product Family Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Product_Family_Short_Title__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_Short_Title__c</fullName>
    <label>Short Title</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Product_Line_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Code__c</fullName>
    <label>Product Line Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Product_line_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_line_Description__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Product_Group_Origin_Description__c</field>
            <operation>equals</operation>
            <valueField>PLM_Product_line_Description__c.Location__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PLM_Product_line_Description__c</referenceTo>
    <relationshipLabel>Product Family</relationshipLabel>
    <relationshipName>Product_Family</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Secondary_Market_Category__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Market_Category__c</fullName>
    <label>Secondary Market Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Primary_Market_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Textbook</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Reference</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/customLookUpController.cls
public class customLookUpController {
    
  
    @AuraEnabled
    public static List < PLM_Product_Family__c  > fetchProductFamily(String searchKeyWord,string ObjectName) {
        String searchKey = searchKeyWord + '%';
        List < PLM_Product_Family__c  > returnList = new List < PLM_Product_Family__c  > ();
        List < PLM_Product_Family__c  > lstOfAccount = [select id, Name,Editor_Name__c,Copy_Product_Family__c,CreatedBy.Name,Full_Title__C,Editor_Code__c,OwnerId,Global_Subject_Category_Code__c, Global_Subject_Category_Description__c,Number_Of_Volumes__c,Primary_Market_Category__c,Product_Family_Name__c,Product_Family_Short_Title__c,Product_Line_Code__c,Product_line_Description__c,Secondary_Market_Category__c from PLM_Product_Family__c where Name LIKE: searchKey OR Full_Title__C Like: searchkey];
        system.debug('lstOfAccount::'+lstOfAccount);
        for (PLM_Product_Family__c  acc: lstOfAccount) {
            returnList.add(acc);
        }
        return returnList;
    }
    
    @AuraEnabled
    public static List < sObject > fetchLookUpValues(String searchKeyWord, String ObjectName) {
        system.debug('ObjectName-->' + ObjectName);
        String searchKey = searchKeyWord;
        List < sObject > returnList = new List < sObject > ();
      
        String sQuery='FIND {' + searchKey + '*} IN NAME FIELDS RETURNING Account(Id,Name), Contact(Id,Name)';
        system.debug('sQuery-->' + sQuery);
        Search.SearchResults searchResults = Search.find(sQuery);
        List<Search.SearchResult> articlelist = searchResults.get(ObjectName);       
        for (Search.SearchResult searchResult : articleList) { 
            if(ObjectName == 'Account'){
                account obj = (Account) searchResult.getSObject();
                returnList.add(obj);
            }else{
                Contact obj = (Contact) searchResult.getSObject();
                returnList.add(obj);
            }           
        }        
        system.debug('returnList::'+returnList);
        return returnList;
    }
    
    
}