force-app/main/default/objects/PLM_Edition__c/PLM_Edition__c.object-meta.xml
<CustomObject>
    <label>Edition</label>
    <nameField>
        <displayFormat>ED-{0000000}</displayFormat>
        <label>Edition #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Editions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WILEY-PLM/force-app/main/default/objects/PLM_Edition__c/fields/Edition_Number1__c.field-meta.xml
<CustomField>
    <fullName>Edition_Number1__c</fullName>
    <label>Edition Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PLM_Edition__c/fields/Edition_Number__c.field-meta.xml
<CustomField>
    <fullName>Edition_Number__c</fullName>
    <formula>Proposal__r.Edition_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Edition Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PLM_Edition__c/fields/Editor_Code__c.field-meta.xml
<CustomField>
    <fullName>Editor_Code__c</fullName>
    <formula>Proposal__r.Editor_Code__c</formula>
    <label>Editor Code</label>
    <type>Text</type>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Edition__c/fields/Global_Subject_Category_Code__c.field-meta.xml
<CustomField>
    <fullName>Global_Subject_Category_Code__c</fullName>
    <formula>Proposal__r.Global_Subject_Category_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Global Subject Category Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Edition__c/fields/Global_Subject_Category_Description__c.field-meta.xml
<CustomField>
    <fullName>Global_Subject_Category_Description__c</fullName>
    <formula>TEXT(Proposal__r.Global_Subject_Category_Description__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Global Subject Category Description</label>
    <type>Text</type>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Edition__c/fields/Number_Of_Volumes__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Volumes__c</fullName>
    <formula>Proposal__r.Number_Of_Volumes__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number Of Volumes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Edition__c/fields/Primary_Market_Category__c.field-meta.xml
<CustomField>
    <fullName>Primary_Market_Category__c</fullName>
    <formula>TEXT( Proposal__r.Primary_Market_Category__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Market Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Edition__c/fields/Product_Family_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_Name__c</fullName>
    <formula>Proposal__r.Product_Family_Name__c</formula>
    <label>Product Family Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Edition__c/fields/Product_Family_Short_Title__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_Short_Title__c</fullName>
    <formula>Proposal__r.Product_Family_Short_Title__c</formula>
    <label>Product Family Short Title</label>
    <type>Text</type>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Edition__c/fields/Product_Line_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Code__c</fullName>
    <formula>Proposal__r.Product_Line_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Line Code</label>
    <type>Text</type>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Edition__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Family</label>
    <referenceTo>PLM_Product_Family__c</referenceTo>
    <relationshipLabel>Editions</relationshipLabel>
    <relationshipName>Editions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PLM_Edition__c/fields/Secondary_Market_Category__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Market_Category__c</fullName>
    <formula>TEXT(Proposal__r.Secondary_Market_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Secondary Market Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/PLM_Product_Family__c.object-meta.xml
<CustomObject>
    <label>Product Family</label>
    <nameField>
        <displayFormat>PF-{0000000}</displayFormat>
        <label>Product Family #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Family</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PLM_Product_Family__c/fields/Copy_Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Copy_Product_Family__c</fullName>
    <label>Copy Product Family</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Product_Family__c/fields/Edition_Number__c.field-meta.xml
<CustomField>
    <fullName>Edition_Number__c</fullName>
    <label>Edition Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Editor_Code__c.field-meta.xml
<CustomField>
    <fullName>Editor_Code__c</fullName>
    <label>Editor Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Editor_Name__c.field-meta.xml
<CustomField>
    <fullName>Editor_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Editor Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Product_Group_Origin_Description__c</field>
            <operation>equals</operation>
            <valueField>PLM_Editor__c.Location__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PLM_Editor__c</referenceTo>
    <relationshipLabel>Product Family</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Product_Family__c/fields/Full_Title__c.field-meta.xml
<CustomField>
    <fullName>Full_Title__c</fullName>
    <label>Full Title</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Global_Subject_Category_Code__c.field-meta.xml
<CustomField>
    <fullName>Global_Subject_Category_Code__c</fullName>
    <label>Global Subject Category Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Global_Subject_Category_Description__c.field-meta.xml
<CustomField>
    <fullName>Global_Subject_Category_Description__c</fullName>
    <label>Global Subject Category Description</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Group_Origin_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>GE Allocated</fullName>
            </value>
            <value>
                <fullName>GE Business</fullName>
            </value>
            <value>
                <fullName>GE Sciences</fullName>
            </value>
            <value>
                <fullName>GE School</fullName>
            </value>
            <value>
                <fullName>GE Microsoft</fullName>
            </value>
            <value>
                <fullName>GE Math and Statistics</fullName>
            </value>
            <value>
                <fullName>GE Engg &amp; Computer Sci</fullName>
            </value>
            <value>
                <fullName>GE Other</fullName>
            </value>
            <value>
                <fullName>GE Applied Markets</fullName>
            </value>
            <value>
                <fullName>GE Social Sciences/Culinary</fullName>
            </value>
            <value>
                <fullName>Undefined</fullName>
            </value>
            <value>
                <fullName>PD Allocated</fullName>
            </value>
            <value>
                <fullName>PD Business</fullName>
            </value>
            <value>
                <fullName>PD Consumer</fullName>
            </value>
            <value>
                <fullName>PD Education</fullName>
            </value>
            <value>
                <fullName>PD Other</fullName>
            </value>
            <value>
                <fullName>PD Psychology</fullName>
            </value>
            <value>
                <fullName>PD Architecture</fullName>
            </value>
            <value>
                <fullName>PD Technology</fullName>
            </value>
            <value>
                <fullName>STMS Allocated</fullName>
            </value>
            <value>
                <fullName>STMS Life Sciences</fullName>
            </value>
            <value>
                <fullName>STMS Health Sciences</fullName>
            </value>
            <value>
                <fullName>STMS Other</fullName>
            </value>
            <value>
                <fullName>STMS Physical Sciences &amp; Engg</fullName>
            </value>
            <value>
                <fullName>STMS Social Sci &amp; Humanities</fullName>
            </value>
            <value>
                <fullName>HE Allocated</fullName>
            </value>
            <value>
                <fullName>HE Business</fullName>
            </value>
            <value>
                <fullName>HE Sciences</fullName>
            </value>
            <value>
                <fullName>HE School</fullName>
            </value>
            <value>
                <fullName>HE Microsoft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Number_Of_Volumes__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Volumes__c</fullName>
    <label>Number Of Volumes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Primary_Market_Category__c.field-meta.xml
<CustomField>
    <fullName>Primary_Market_Category__c</fullName>
    <label>Primary Market Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Textbook</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Reference</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Product_Family__c/fields/Product_Family_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_Name__c</fullName>
    <label>Product Family Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Product_Family_Short_Title__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_Short_Title__c</fullName>
    <label>Short Title</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Product_Line_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Line_Code__c</fullName>
    <label>Product Line Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Product_line_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_line_Description__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Line</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Product_Group_Origin_Description__c</field>
            <operation>equals</operation>
            <valueField>PLM_Product_line_Description__c.Location__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PLM_Product_line_Description__c</referenceTo>
    <relationshipLabel>Product Family</relationshipLabel>
    <relationshipName>Product_Family</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Secondary_Market_Category__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Market_Category__c</fullName>
    <label>Secondary Market Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Primary_Market_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Textbook</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Reference</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PLM_Proposal__c/PLM_Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PLM_Proposal__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This is the description.</description>
    <label>Description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Proposal__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Family</label>
    <referenceTo>PLM_Product_Family__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PLM_Proposal__c/fields/Proposal_Name__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Name__c</fullName>
    <description>This is the Proposal name.</description>
    <label>Proposal Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PLM_ProjectOverride.cls
/**********************************************************************
Name: PLM_ProjectOverride()
Copyright © 2015 Salesforce
======================================================
======================================================
@Purpose: Linked to Proposal Screen component PLM_COMP_ProjectOverride.
======================================================
======================================================
History 
------- 
VERSION   AUTHOR                  DATE        DETAIL Description
1.0       Name : Abilash Patha   30/07/2019   INITIAL DEVELOPMENT CSR: 
***********************************************************************/
public With Sharing class PLM_ProjectOverride {
   public static List<RecordType> propRecTypeList;
   public static String recPropName;
   public static Id finRecId;
   public static List<RecordType> prodFamRecTypeList;
   public static PLM_Product_Family__c prodFamilyNewRec;
   public static PLM_Proposal__c propRecordCre;
	
    /**
     * @Purpose: To get the record type Id of Product Family. 
     * @Returns: Product Family record type Id.
     * @Parameters:  Record type id of Proposal selected in the first screen in the Component. 
     */
    @auraEnabled
    public static Id recordTypeByName(Id recId){
        propRecTypeList = new List<RecordType>();
        prodFamRecTypeList = new List<RecordType>();
        try{  
            system.debug('in apex project override class'+recId);
           propRecTypeList = [SELECT Id, SobjectType, Name, DeveloperName FROM RecordType WHERE SobjectType='PLM_Proposal__c' and Id=: recId LIMIT 1];
            if(propRecTypeList.size() > 0){
            	recPropName = propRecTypeList[0].Name;
            
               prodFamRecTypeList = [SELECT Id, SobjectType, Name, DeveloperName FROM RecordType WHERE SobjectType='PLM_Product_Family__c' and Name=: recPropName LIMIT 1];
                system.debug('final rec id'+prodFamRecTypeList);
                if(prodFamRecTypeList.size() > 0){
                    finRecId = prodFamRecTypeList[0].Id;
                    return finRecId;
                }else{
                    return null;
                }
            }else{
                return null;
            }
        }catch(exception e){
            system.debug('Exception occured in recordTypeByName method at Line '+ e.getLineNumber() +' Error Message '+e.getMessage());
            return null;
        }
    }
    @auraEnabled
    public static String recordTypeByNameForProposal(Id recId){
        propRecTypeList = new List<RecordType>();
        prodFamRecTypeList = new List<RecordType>();
        try{  
            system.debug('in apex project override class'+recId);
           propRecTypeList = [SELECT Id, SobjectType, Name, DeveloperName FROM RecordType WHERE SobjectType='PLM_Proposal__c' and Id=: recId LIMIT 1];
            if(propRecTypeList.size() > 0){
            	recPropName = propRecTypeList[0].Name;
                return recPropName;
			}else{
                return null;
            }
        }catch(exception e){
            system.debug('Exception occured in recordTypeByNameForProposal method at Line '+ e.getLineNumber() +' Error Message '+e.getMessage());
            return null;
        }
    }
    @auraEnabled
    public static string CreateEdition(PLM_Product_Family__c productFamily,Integer edititonNumber){
        string message = '';
        system.debug('productFamily Edit Number::'+productFamily.Edition_Number__c);
        system.debug(' Edition Number::'+edititonNumber);
        try{
            
            if(productFamily != Null)
            {
                update productFamily;
                system.debug('Product family ');
                PLM_Edition__c newedition = new PLM_Edition__c();
                newedition.Proposal__c = productFamily.Id;
                newEdition.Edition_Number1__c = edititonNumber;
                insert newEdition;
                 message= newEdition.id;
            }
            
            }
        catch(exception e)
        {
            message= 'Edition Record Creation Failed';
        }
        
        return message;
    }
    
     /**
     * @Purpose: To create Product Family & Proposal. 
     * @Returns: Product Family record type Id.
     * @Parameters: All the values of Product family. 
     */
    @auraEnabled 
    public static string createProductFamily(String cProdFam,string editNum,string fullTitle,string globalSubCatDescr,
                                             string primaryMktCat, string prodFamShrtTitle, string nameOfProd, 
                                             string editCode, string globSubCatCode, string numbOfVol, string prodFamName, 
                                             string prodLineCode, string secondMarCat, string editorName, string ProposalName,string Description){
        string message = '';
           system.debug('@#@#@#@#@#'+fullTitle);
        try{
           	prodFamilyNewRec = new PLM_Product_Family__c();
            prodFamilyNewRec.Copy_Product_Family__c = cProdFam;
            //prodFamilyNewRec.Edition_Number__c = editNum;
            prodFamilyNewRec.Full_Title__c = fullTitle;
            prodFamilyNewRec.Global_Subject_Category_Description__c = globalSubCatDescr;
            prodFamilyNewRec.Primary_Market_Category__c = primaryMktCat;
            prodFamilyNewRec.Product_Family_Short_Title__c = prodFamShrtTitle;
            //prodFamilyNewRec.Product_line_Description__c =  prodLineDescr;
            //prodFamilyNewRec.Name
            prodFamilyNewRec.Editor_Code__c = editCode;
            prodFamilyNewRec.Global_Subject_Category_Code__c = globSubCatCode;
            //prodFamilyNewRec.Number_Of_Volumes__c = numbOfVol;
            prodFamilyNewRec.Product_Family_Name__c = prodFamName;
            prodFamilyNewRec.Product_Line_Code__c = prodLineCode;
            prodFamilyNewRec.Secondary_Market_Category__c = secondMarCat;
            prodFamilyNewRec.Editor_Name__c = editorName;
            system.debug('#############0'+Description);
            insert prodFamilyNewRec;
  			system.debug('#############'+ProposalName);
            propRecordCre = new PLM_Proposal__c();
            propRecordCre.Proposal_Name__c = ProposalName;
            propRecordCre.Product_Family__c = prodFamilyNewRec.ID;
            propRecordCre.Description__c = Description;
            insert propRecordCre;
            system.debug('#$#$#$'+propRecordCre.Id);
            message= propRecordCre.Id;
            }
        catch(exception e)
        {
            	system.debug('@#@#@#@#@#'+e.getMessage());
			 message= 'Product Family Record Creation Failed';
        }
        
        return message;
    }
    
     @auraEnabled
    public static Temp_Proposal__c setTempProposal(Temp_Proposal__c tempProposal){
       tempProposal.Name=userInfo.getUserName();
       Database.insert(tempProposal);
       return tempProposal;
    }
}