force-app/main/default/objects/PLM_Author__c/PLM_Author__c.object-meta.xml
<CustomObject>
    <label>Author</label>
    <nameField>
        <label>Author Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WILEY-PLM/force-app/main/default/objects/PLM_Author__c/fields/Editor_Name__c.field-meta.xml
<CustomField>
    <fullName>Editor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Editor Name</label>
    <referenceTo>PLM_Editor__c</referenceTo>
    <relationshipLabel>Authors</relationshipLabel>
    <relationshipName>Authors</relationshipName>
    <type>Lookup</type>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Author__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Location</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PLM_Edition__c/PLM_Edition__c.object-meta.xml
<CustomObject>
    <label>Edition</label>
    <nameField>
        <displayFormat>ED-{0000000}</displayFormat>
        <label>Edition #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Editions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PLM_Edition__c/fields/Edition_Number__c.field-meta.xml
<CustomField>
    <fullName>Edition_Number__c</fullName>
    <formula>Proposal__r.Edition_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Edition Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PLM_Edition__c/fields/Global_Subject_Category_Description__c.field-meta.xml
<CustomField>
    <fullName>Global_Subject_Category_Description__c</fullName>
    <formula>TEXT(Proposal__r.Global_Subject_Category_Description__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Global Subject Category Description</label>
    <type>Text</type>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Edition__c/fields/Number_Of_Volumes__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Volumes__c</fullName>
    <formula>Proposal__r.Number_Of_Volumes__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number Of Volumes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Edition__c/fields/Primary_Market_Category__c.field-meta.xml
<CustomField>
    <fullName>Primary_Market_Category__c</fullName>
    <formula>TEXT( Proposal__r.Primary_Market_Category__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Market Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Edition__c/fields/Product_Family_Short_Title__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_Short_Title__c</fullName>
    <formula>Proposal__r.Product_Family_Short_Title__c</formula>
    <label>Product Family Short Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Edition__c/fields/Product_Group_Origin_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Group_Origin_Description__c</fullName>
    <formula>TEXT( Proposal__r.Product_Group_Origin_Description__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Group (Origin) Description</label>
    <type>Text</type>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Edition__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Family</label>
    <referenceTo>PLM_Product_Family__c</referenceTo>
    <relationshipLabel>Editions</relationshipLabel>
    <relationshipName>Editions</relationshipName>
    <type>Lookup</type>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Product_Family__c/PLM_Product_Family__c.object-meta.xml
<CustomObject>
    <label>Product Family</label>
    <nameField>
        <displayFormat>PF-{0000000}</displayFormat>
        <label>Product Family #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Family</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PLM_Product_Family__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Author</label>
    <referenceTo>PLM_Author__c</referenceTo>
    <relationshipLabel>Product Family</relationshipLabel>
    <relationshipName>Product_Family</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Product_Family__c/fields/Edition_Number__c.field-meta.xml
<CustomField>
    <fullName>Edition_Number__c</fullName>
    <label>Edition Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Editor_Name__c.field-meta.xml
<CustomField>
    <fullName>Editor_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Editor Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Product_Group_Origin_Description__c</field>
            <operation>equals</operation>
            <valueField>PLM_Editor__c.Location__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>PLM_Editor__c</referenceTo>
    <relationshipLabel>Product Family</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Product_Family__c/fields/Full_Title__c.field-meta.xml
<CustomField>
    <fullName>Full_Title__c</fullName>
    <label>Full Title</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Product_Family__c/fields/Global_Subject_Category_Description__c.field-meta.xml
<CustomField>
    <fullName>Global_Subject_Category_Description__c</fullName>
    <label>Global Subject Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Group_Origin_Description__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>GE Allocated</fullName>
            </value>
            <value>
                <fullName>GE Business</fullName>
            </value>
            <value>
                <fullName>GE Sciences</fullName>
            </value>
            <value>
                <fullName>GE School</fullName>
            </value>
            <value>
                <fullName>GE Microsoft</fullName>
            </value>
            <value>
                <fullName>GE Math and Statistics</fullName>
            </value>
            <value>
                <fullName>GE Engg &amp; Computer Sci</fullName>
            </value>
            <value>
                <fullName>GE Other</fullName>
            </value>
            <value>
                <fullName>GE Applied Markets</fullName>
            </value>
            <value>
                <fullName>GE Social Sciences/Culinary</fullName>
            </value>
            <value>
                <fullName>Undefined</fullName>
            </value>
            <value>
                <fullName>PD Allocated</fullName>
            </value>
            <value>
                <fullName>PD Business</fullName>
            </value>
            <value>
                <fullName>PD Consumer</fullName>
            </value>
            <value>
                <fullName>PD Education</fullName>
            </value>
            <value>
                <fullName>PD Other</fullName>
            </value>
            <value>
                <fullName>PD Psychology</fullName>
            </value>
            <value>
                <fullName>PD Architecture</fullName>
            </value>
            <value>
                <fullName>PD Technology</fullName>
            </value>
            <value>
                <fullName>STMS Allocated</fullName>
            </value>
            <value>
                <fullName>STMS Life Sciences</fullName>
            </value>
            <value>
                <fullName>STMS Health Sciences</fullName>
            </value>
            <value>
                <fullName>STMS Other</fullName>
            </value>
            <value>
                <fullName>STMS Physical Sciences &amp; Engg</fullName>
            </value>
            <value>
                <fullName>STMS Social Sci &amp; Humanities</fullName>
            </value>
            <value>
                <fullName>HE Allocated</fullName>
            </value>
            <value>
                <fullName>HE Business</fullName>
            </value>
            <value>
                <fullName>HE Sciences</fullName>
            </value>
            <value>
                <fullName>HE School</fullName>
            </value>
            <value>
                <fullName>HE Microsoft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Number_Of_Volumes__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Volumes__c</fullName>
    <label>Number Of Volumes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/PFRD__c.field-meta.xml
<CustomField>
    <fullName>PFRD__c</fullName>
    <label>Projected First Receipt Date</label>
    <type>Date</type>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Product_Family__c/fields/Primary_Market_Category__c.field-meta.xml
<CustomField>
    <fullName>Primary_Market_Category__c</fullName>
    <label>Primary Market Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Textbook</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Reference</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Product_Family_Short_Title__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_Short_Title__c</fullName>
    <label>Short Title</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/fields/Product_Group_Origin_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Group_Origin_Description__c</fullName>
    <label>Product Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Location</valueSetName>
    </valueSet>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Product_Family__c/fields/Product_line_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_line_Description__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Line</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Product_Group_Origin_Description__c</field>
            <operation>equals</operation>
            <valueField>PLM_Product_line_Description__c.Location__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>PLM_Product_line_Description__c</referenceTo>
    <relationshipLabel>Product Family</relationshipLabel>
    <relationshipName>Product_Family</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PLM_Product_Family__c/recordTypes/Reference.recordType-meta.xml
<RecordType>
    <fullName>Reference</fullName>
    <active>true</active>
    <label>Reference</label>
</RecordType>

force-app/main/default/objects/PLM_Proposal__c/PLM_Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PLM_Proposal__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This is the description.</description>
    <label>Description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Proposal__c/fields/PFRD__c.field-meta.xml
<CustomField>
    <fullName>PFRD__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PLM_Proposal__c/fields/Proposal_Name__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Name__c</fullName>
    <description>This is the Proposal name.</description>
    <label>Proposal Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

WILEY-PLM/force-app/main/default/objects/PLM_Proposal__c/recordTypes/Reference.recordType-meta.xml
<RecordType>
    <fullName>Reference</fullName>
    <active>true</active>
    <label>Reference</label>
</RecordType>

force-app/main/default/objects/PLM_Proposal__c/recordTypes/Wiley.recordType-meta.xml
<RecordType>
    <fullName>Wiley</fullName>
    <active>true</active>
    <label>Wiley Efficient Learning(WEL)</label>
</RecordType>

force-app/main/default/objects/PLM_Temporary_Proposal__c/PLM_Temporary_Proposal__c.object-meta.xml
<CustomObject>
    <label>Temporary Proposal</label>
    <nameField>
        <displayFormat>TP-{0000000}</displayFormat>
        <label>Temporary Proposal  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Temporary Proposal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WILEY-PLM/force-app/main/default/objects/PLM_Temporary_Proposal__c/fields/Edition_Number__c.field-meta.xml
<CustomField>
    <fullName>Edition_Number__c</fullName>
    <label>Edition Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PLM_Temporary_Proposal__c/fields/PFRD__c.field-meta.xml
<CustomField>
    <fullName>PFRD__c</fullName>
    <label>PFRD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PLM_Temporary_Proposal__c/fields/Proposal_Name__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Name__c</fullName>
    <label>Proposal Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Location.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <customValue>
        <fullName>Asia</fullName>
    </customValue>
    <customValue>
        <fullName>Canada</fullName>
    </customValue>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <masterLabel>Location</masterLabel>
</GlobalValueSet>

WILEY-PLM/force-app/main/default/classes/PLM_TestDataUtility.cls
/**********************************************************************
Name: PLM_TestDataUtility
Copyright © 2015 Salesforce
======================================================
======================================================
@Purpose: Test Data Utility Class to maintain and reusable code for Entire Project
======================================================
***********************************************************************/

/**
      * @Description: Create/Update/Read Test Data for all Test Classes.
**/
public class PLM_TestDataUtility {

	/**
      * @Description: Test method for the Creation of temp proposal data
      * @Params                  : NA                                                                                  
      * @return                  : PLM_Temporary_Proposal__c object
      */
    public static PLM_Temporary_Proposal__c createTempProposalData(){
        PLM_Temporary_Proposal__c tempPropData = new PLM_Temporary_Proposal__c();
        tempPropData.Description__c = 'WileyPLM Description';
        tempPropData.Edition_Number__c = 789.00;
        tempPropData.Proposal_Name__c = 'Wiley Products';
        tempPropData.PFRD__c = Date.today();
        
        insert tempPropData;
        return tempPropData;
    }
    
    /**
      * @Description: Test method for the Creation of proposal data
      * @Params                  : NA                                                                                  
      * @return                  : PLM_Proposal__c object
      */
     public static PLM_Proposal__c createProposalData(){
       PLM_Proposal__c testProposal =  new PLM_Proposal__c();
       testProposal.Proposal_Name__c = 'Wiley Proposal';
       testProposal.Edition_Number__c = 1234;
       testProposal.Description__c = 'Prop Descr';
         
       insert testProposal;
       return testProposal;
    }

    /**
      * @Description: Test method for the Creation of Author data
      * @Params                  : NA                                                                                  
      * @return                  : PLM_Author__c object
      */
    public static PLM_Author__c createAuthor(){
     PLM_Author__c Au= New PLM_Author__c();
     Au.Name='Test Author';
     Au.Location__c='Germany';
     return Au;
    }
    
     /**
      * @Description: Test method for the Creation of Product Line Description data
      * @Params                  : NA                                                                                  
      * @return                  : PLM_Product_line_Description__c object
      */
     public static PLM_Product_line_Description__c createProductLineDescription(){
     PLM_Product_line_Description__c Pl = New PLM_Product_line_Description__c();
     Pl.Name='Test Product Line';
     Pl.Location__c='Germany';
     //insert Pl;
     return  Pl;
     }

     /**
      * @Description: Test method for the Creation of Editor data
      * @Params                  : NA                                                                                  
      * @return                  : PLM_Editor__c object
      */
    public static PLM_Editor__c createEditor(){
    PLM_Editor__c Edtr = New PLM_Editor__c();
    Edtr.Name='Test Editor';
    Edtr.Location__c='Germany';
    //insert Edtr;
    return Edtr;
    }

    /**
      * @Description: Test method for the Creation of Product Family data
      * @Params                  : NA                                                                                  
      * @return                  : PLM_Product_Family__c object
      */
     public static PLM_Product_Family__c createProductFamily(Id AuthorId,Id PldId,Id EdtrId){
     PLM_Product_Family__c Pf = New PLM_Product_Family__c();
     Pf.Edition_Number__c=1;
     Pf.Edition_Number__c=1;
     Pf.Number_Of_Volumes__c=1;
     Pf.Product_Family_Short_Title__c='Short test';
     Pf.Full_Title__c='Full Test';
     Pf.Product_Group_Origin_Description__c='Germany';
     Pf.Author__c=AuthorId;
     Pf.Product_line_Description__c=PldId;
     Pf.Editor_Name__c=EdtrId;
     Pf.Global_Subject_Category_Description__c='PD Allocated';
     Pf.Primary_Market_Category__c='Textbook';
     Pf.RecordTypeId=Schema.SObjectType.PLM_Product_Family__c.getRecordTypeInfosByName().get('Reference').getRecordTypeId();
    // insert Pf;
     return Pf;
     }

     /**
      * @Description: Test method for the Creation of Edition data
      * @Params                  : NA                                                                                  
      * @return                  : PLM_Edition__c object
      */
    public static PLM_Edition__c createEdition(Id PfId){
     PLM_Edition__c Edtn= New PLM_Edition__c();
     Edtn.Edition_Number1__c=1;
     Edtn.Proposal__c=PfId;
     //insert Edtn;
     return Edtn;
    }
}
/**********************************************************************
======================================================
History Check new comments 22 444   dsdfasd
------- 
VERSION   AUTHOR                  			DATE        DETAIL Description
1.0       Name : Offshore Team           08/08/2019  INITIAL DEVELOPMENT CSR: 
***********************************************************************/